### ISSUE TITLE
Fishing jobs

### ISSUE THREAD

**Issue by younesdev123** [Stuyk/altV-Open-Roleplay#123]
[14:48:36][Error] [V8] Exception at orp:file:///home/orp/resources/orp/server/systems/job.mjs:459
[14:48:36][Error]               if (baseItem.abilities.stack) {
[14:48:36][Error]   TypeError: Cannot read property 'abilities' of undefined
    at file:///home/orp/resources/orp/server/systems/job.mjs:459:26
    at Array.forEach (<anonymous>)
    at Objective.giveRewards (file:///home/orp/resources/orp/server/systems/job.mjs:454:22)
    at Objective.finishObjective (file:///home/orp/resources/orp/server/systems/job.mjs:306:14)
    at Objective.attemptObjective (file:///home/orp/resources/orp/server/systems/job.mjs:299:14)
    at Job.check (file:///home/orp/resources/orp/server/systems/job.mjs:1030:33)
    at check (file:///home/orp/resources/orp/server/systems/job.mjs:1069:16)

**Comment by Stuyk** [comment]
Unable to reproduce.
