### ISSUE TITLE
TypeError: player.emitMeta is not a function

### ISSUE THREAD

**Issue by Setraxis** [Stuyk/altV-Open-Roleplay#126]
### Describe the bug (What the bug is)
```log
[22:01:34][Error] [V8] Exception at orp:file:///home/altv/altv-server/resources/orp/server/systems/interaction.mjs:109
[22:01:34][Error]       player.emitMeta('interaction', undefined);
[22:01:34][Error]   TypeError: player.emitMeta is not a function
    at Module.clearInteraction (file:///home/altv/altv-server/resources/orp/server/systems/interaction.mjs:109:12)
    at file:///home/altv/altv-server/resources/orp/server/events/entityLeaveColshape.mjs:7:28
[22:01:34][Error] [V8] Exception at orp:file:///home/altv/altv-server/resources/orp/server/systems/interaction.mjs:109
[22:01:34][Error]       player.emitMeta('interaction', undefined);
[22:01:34][Error]   TypeError: player.emitMeta is not a function
    at Module.clearInteraction (file:///home/altv/altv-server/resources/orp/server/systems/interaction.mjs:109:12)
    at file:///home/altv/altv-server/resources/orp/server/events/entityLeaveColshape.mjs:7:28

```

### Reproducing the Bug (Steps)
1. Open...
2. Do...
3. Close...
4. ???
5. Profit

### Potential Solution Description (Optional)
Describe how you want this bug fixed.

**Comment by Stuyk** [comment]
Can you confirm that this is fixed in the latest update to master? @Setraxis
